# Generated by Django 2.1.2 on 2018-11-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20181107_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Preço'),
        ),
    ]
